### ISSUE TITLE
i cant build it 

### ISSUE THREAD

**Issue by apol3t** [ZTzTopia/GrowtopiaImGui#12]
i get this error i try to use conan 1.55.0 but doesnot work how can i fix it ?

**Comment by ZTzTopia** [comment]
There are no errors from conan, can you provide the full log?

You created an issue in the wrong repository.

**Comment by apol3t** [comment]
how can i get full log ?

**Comment by ZTzTopia** [comment]
I mean copy all text from terminal and paste it here.

**Comment by apol3t** [comment]
okey wait and sorry with this "You created an issue in the wrong repository."

**Comment by apol3t** [comment]
here it is https://justpaste.it/

**Comment by ZTzTopia** [comment]
Ah did you clone it? if yes you need to add options `--recurse-submodules` repeat the command with this `git clone --recurse-submodules https://github.com/ZTzTopia/GTProxy.git`

**Comment by apol3t** [comment]
ohh okey

**Comment by apol3t** [comment]
its worked now ty sir

**Comment by celikj** [comment]
alper ismin sanirim bro bana ulas ya beceremedim build etmeyi ig:firatcelikj

**Comment by apol3t** [comment]
readme de nasıl build ediliceği yazıyor nerde hata alıyorsan bi issue oluştur senin için daha iyi olur
